---
os: linux
arch: amd64
dist: bionic
version: "~> 1.0"
language: python
cache:
  edge: true
  apt: true
  pip: true

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "2.7"

jobs:
  fast_finish: true

virtualenv:
  system_site_packages: true

git:
  autocrlf: input

addons:
  apt:
    dist: bionic
    update: true
    sources:
    - deadsnakes
    packages:
    - check-manifest
    - python-flake8
    - python-pyroma
    - python3-flake8
    - python3-pyroma
    - twine

install:
  - pip install -UI --pre pip setuptools
  - pip install -UI --pre check-manifest flake8 pyroma twine

script:
  - python -m compileall -f .
  - test/test.py --unit --exit-early
  - test/test.py --exit-early
  - pyroma -n 9 .
  - check-manifest .
  - flake8 --exclude=build,venv --ignore= --max-line-length=200 --max-complexity=75 --show-source --statistics .
  - python setup.py sdist bdist_wheel
  - twine check dist/*
